# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pines_pipeline_monociclo.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/Data_Memory/Data_Memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Data_Memory || ORIG_REF_NAME==Data_Memory} -quiet] -quiet

# IP: ip/Instruction_memory/Instruction_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Instruction_memory || ORIG_REF_NAME==Instruction_memory} -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: ip/Instruction_memory/Instruction_memory_ooc.xdc
